name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gopalsaini/wsi-slides-dzi-processor:latest

    - name: Scan Docker image for vulnerabilities
      uses: docker/scout-action@v1
      with:
        command: cves
        image: gopalsaini/wsi-slides-dzi-processor:latest
        only-severities: critical,high
        sarif-file: scout-report.sarif
      continue-on-error: true

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: scout-report.sarif

    - name: Push the Docker image
      run: docker push gopalsaini/wsi-slides-dzi-processor:latest